CREATE VIEW VIDA60 AS 
SELECT * FROM COUNTRY
WHERE LifeExpectancy >= 60;

select * from VIDA60;

SELECT CITY.NAME FROM CITY JOIN VIDA60 ON COUNTRYCODE = CODE WHERE CONTINENT = 'EUROPE';

-- CIUDAD Y PAIS AL QUE PERTENECE. COLUMNAS REPETIDAS

CREATE VIEW CIUDAD_PAIS AS
SELECT COUNTRY.NAME COUNTRY, CITY.NAME CITY FROM CITY JOIN COUNTRY ON COUNTRYCODE = CODE;

SELECT * FROM CIUDAD_PAIS;

DROP VIEW CIUDAD_PAIS;

CREATE VIEW CIUDAD_PAIS(PAIS, CIUDAD) AS
SELECT COUNTRY.NAME, CITY.NAME FROM CITY JOIN COUNTRY ON COUNTRYCODE = CODE;

SELECT * FROM CIUDAD_PAIS;


CREATE OR REPLACE VIEW MAX_MIN_POPULATION AS
SELECT CONTINENT, MAX(POPULATION), MIN(POPULATION)
FROM country
GROUP BY CONTINENT;

-- MEJOR DARLE UN NOMBRE A LA TABLA DESDE EL CREATE

CREATE OR REPLACE VIEW MAX_MIN_POPULATION(CONTINENTE, POB_MAX, POB_MIN) AS
SELECT CONTINENT, MAX(POPULATION), MIN(POPULATION)
FROM country
GROUP BY CONTINENT;

SELECT * FROM MAX_MIN_POPULATION;


/*  UPDATABLES VIEW */

/* 
	permiten insertar, actualizar y borrar datos en als tablas que hay bajo la vista
    
    No podemos tener:
     - Funciones de agregacion Min, Max, etc
     - Group by
     - Distinct
     - Uniones
     - Left join
     - Subconsultas
*/

CREATE TABLE TABLA_VISTA
(codigo int primary key,
nombre varchar(100) not null);

CREATE OR REPLACE VIEW VISTA AS SELECT * FROM TABLA_VISTA;

SELECT * FROM VISTA;

INSERT INTO TABLA_VISTA VALUES (1, 'PACO');
INSERT INTO TABLA_VISTA VALUES (2, 'MARIA');

-- INSERCIÓN A TRAVES DE LA VISTA
INSERT INTO VISTA VALUES (3, 'LAURA');

-- BORRAR A TRAVES DE LA VISTA

DELETE FROM VISTA WHERE CODIGO = 3;

-- MODIFICAR A TRAVES DE LA VISTA

UPDATE VISTA SET NOMBRE = 'CONQUER' WHERE CODIGO = 1;

-- VISTAS NO UPDATABLE
-- NO TENGO SUFICIENTES COLUMNAS DEFINIDAS

CREATE OR REPLACE VIEW VISTA1 AS 
SELECT NOMBRE FROM TABLA_VISTA;

SELECT * FROM VISTA1;
-- EN ESTE CASO FALTARIAN COLUMNAS POR DEFINIR
INSERT INTO VISTA1 VALUES("ALBERTO");

CREATE OR REPLACE VIEW VISTA2
AS SELECT NOMBRE, COUNT(*) FROM TABLA_VISTA
group by NOMBRE;

SELECT * FROM VISTA2;

INSERT INTO VISTA2 VALUES('RAUL', 20);


SELECT * FROM VISTA;

INSERT INTO VISTA values (3, "XXXXX");
INSERT INTO VISTA values (23, "XXXXX");

CREATE OR REPLACE VIEW VISTA_CHECK AS
SELECT * FROM TABLA_VISTA WHERE CODIGO>4;

SELECT * FROM VISTA_CHECK;

INSERT INTO VISTA_CHECK VALUES(4, "VISTA");

SELECT * FROM TABLA_VISTA;

-- CHECK OPTION
/* CON EL "WITH CHECK OPTION" TIENE EN CUENTA LOS FILTROS
*/

CREATE OR REPLACE VIEW VISTA_CHECK AS
SELECT * FROM TABLA_VISTA WHERE CODIGO>4
WITH CHECK OPTION;

INSERT INTO VISTA_CHECK VALUES(4, "VISTA");

-- RENOMBRADO Y EL BORRADO DE VISTA

RENAME TABLE VISTA TO VISTA_NUEVA;
SELECT * FROM VISTA_NUEVA;

DROP VIEW IF EXISTS VISTA_NUEVA;